sudo: false
dist: trusty

script:
 - yarn build
 - node ./scripts/preload.js
 - chmod +x ./ossutil64
 - ./ossutil64 config -e $OSS_ENDPOINT -i $OSS_ID -k $OSS_KEY
 - if [ $TRAVIS_BRANCH  ] && [ $TRAVIS_BRANCH = "master" ]; then
      ./ossutil64 cp -r ./dist oss://$OSS_BUCKETNAME --update;
   fi